const board=document.querySelector('#board'),startBtn=document.querySelector('#startBtn'),energyToggle=document.querySelector('.hero-actions input[type="checkbox"]'),hackModeButton=document.querySelector('#hackModeButton'),message=document.querySelector('#message'),shop=document.querySelector('.shop'),sunCountEl=document.querySelector('#sunCount'),waveCountEl=document.querySelector('#waveCount'),scoreCountEl=document.querySelector('#scoreCount'),lifeCountEl=document.querySelector('#lifeCount'),bestCountEl=document.querySelector('#bestCount');
const ROWS=5,COLS=9,MAX_WAVE=15,KILLS_PER_WAVE=8;
const PLANTS={pea:{icon:'🌿',cost:50,hp:125,rate:1350,dmg:24},frost:{icon:'❄️',cost:85,hp:105,rate:1650,dmg:14,slow:1700},laser:{icon:'🔆',cost:125,hp:105,rate:2100,dmg:22,pierce:true},bomb:{icon:'💣',cost:100,hp:80,dmg:180,bomb:true},sun:{icon:'🌻',cost:75,hp:95,sunEvery:6000},wall:{icon:'🪵',cost:40,hp:420}};
const ZT={basic:{i:'🧟',hp:80,sp:13,hit:25,pt:10,en:25},fast:{i:'🏃',hp:60,sp:24,hit:20,pt:12,en:25},shield:{i:'🛡️',hp:135,sp:10,hit:28,pt:16,en:35},armor:{i:'🪖',hp:190,sp:8,hit:32,pt:22,en:45},giant:{i:'🧌',hp:320,sp:6,hit:42,pt:40,en:65},boss:{i:'👹',hp:650,sp:5,hit:55,pt:120,en:150}};
let selectedPlant='pea',sun=150,wave=1,kills=0,score=0,lives=5,bestScore=Number(localStorage.getItem('gardenDefenseBest')||0),infiniteEnergy=false,isPlaying=false,lastFrame=performance.now(),lastSpawn=0,spawnEvery=3500,bossOut=false,zid=1;const cells=[],plants=new Map(),zombies=[],projectiles=[];
let audioCtx=null,lastSfx={};function audioStart(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!audioCtx&&AC)audioCtx=new AC();if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume()}catch(e){}}
function beep(freq,dur=.08,delay=0,type='sine',vol=.045){if(!audioCtx)return;const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur+.02)}
function sfx(name){if(!audioCtx)return;const now=performance.now(),gap={shoot:90,bite:300,kill:120,sun:160}[name]||40;if(lastSfx[name]&&now-lastSfx[name]<gap)return;lastSfx[name]=now;if(name==='plant')return beep(520,.07,0,'triangle'),beep(720,.08,.06,'triangle');if(name==='shoot')return beep(720,.045,0,'square',.018);if(name==='laser')return beep(980,.06,0,'sawtooth',.025);if(name==='sun')return beep(660,.07,0,'sine'),beep(880,.09,.07,'sine');if(name==='kill')return beep(260,.06,0,'square'),beep(160,.07,.05,'square');if(name==='boom')return beep(90,.18,0,'sawtooth',.08),beep(55,.22,.04,'sawtooth',.06);if(name==='wave')return beep(520,.08,0),beep(660,.08,.08),beep(880,.12,.16);if(name==='boss')return beep(110,.22,0,'sawtooth',.07),beep(82,.26,.08,'sawtooth',.06);if(name==='deny')return beep(180,.08,0,'square'),beep(140,.08,.08,'square');if(name==='gameover')return beep(240,.12,0,'triangle'),beep(180,.14,.12,'triangle'),beep(120,.2,.26,'triangle');if(name==='start')return beep(440,.08,0),beep(660,.08,.08),beep(880,.1,.16);if(name==='bite')return beep(120,.05,0,'square',.025);if(name==='mode')return beep(700,.08,0),beep(980,.12,.08)}
function initShop(){shop.innerHTML=`<button class="plant-card selected" data-plant="pea"><span class="plant-icon">🌿</span><b>Pea Ranger</b><small>50 ☀️ · Tự nâng cấp</small></button><button class="plant-card" data-plant="frost"><span class="plant-icon">❄️</span><b>Frost Pea</b><small>85 ☀️ · Làm chậm</small></button><button class="plant-card" data-plant="laser"><span class="plant-icon">🔆</span><b>Laser Flower</b><small>125 ☀️ · Bắn xuyên</small></button><button class="plant-card" data-plant="bomb"><span class="plant-icon">💣</span><b>Cherry Bomb</b><small>100 ☀️ · Nổ cùng hàng</small></button><button class="plant-card" data-plant="sun"><span class="plant-icon">🌻</span><b>Sun Bloom</b><small>75 ☀️ · Sinh nắng</small></button><button class="plant-card" data-plant="wall"><span class="plant-icon">🪵</span><b>Wood Guardian</b><small>40 ☀️ · Chặn zombie</small></button>`;document.querySelectorAll('.plant-card').forEach(btn=>btn.addEventListener('click',()=>{audioStart();sfx('plant');document.querySelectorAll('.plant-card').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');selectedPlant=btn.dataset.plant;setMessage('Đã chọn '+btn.querySelector('b').textContent)}));const guide=document.createElement('section');guide.className='message';guide.innerHTML='<b>Wave:</b> 15 wave chính + Endless. Wave 4 có khiên, wave 6 có giáp, wave 9 có giant, wave 5/10/15 có boss. Pea Ranger lên cấp ở wave 4, 8, 12.';message.before(guide)}
function buildBoard(){board.innerHTML='';cells.length=0;for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const cell=document.createElement('button');cell.className='cell';cell.addEventListener('click',()=>plantAt(r,c,cell));board.appendChild(cell);cells.push(cell)}}
function lvl(){return wave>=12?4:wave>=8?3:wave>=4?2:1}function displayWave(){return wave<=MAX_WAVE?wave+'/'+MAX_WAVE:'Endless '+(wave-MAX_WAVE)}function updateHUD(){sunCountEl.textContent=infiniteEnergy?'∞':sun;waveCountEl.textContent=displayWave();scoreCountEl.textContent=score;lifeCountEl.textContent=lives;if(bestCountEl)bestCountEl.textContent=bestScore}function setMessage(t){message.textContent=t}
function setEnergyMode(v){audioStart();infiniteEnergy=v;if(energyToggle)energyToggle.checked=v;document.body.classList.toggle('hack-on',v);if(hackModeButton){hackModeButton.textContent=v?'✅ HACK MODE ĐANG BẬT / ∞ ENERGY':'⚡ BẬT HACK MODE / ∞ ENERGY';hackModeButton.style.background=v?'linear-gradient(135deg,#25d366,#0b8f3a)':'linear-gradient(135deg,#ffcf33,#ff8a00)';hackModeButton.style.color=v?'#fff':'#281800'}updateHUD();sfx('mode');setMessage(v?'Hack Mode đã bật: năng lượng ∞':'Hack Mode đã tắt 🌱')}
function stats(p){const d=PLANTS[p.type],l=lvl();let s={...d,l};if(p.type==='pea'){s.dmg=d.dmg+(l-1)*14;s.rate=Math.max(720,d.rate-(l-1)*180);s.extra=l>=4?2:l>=3?1:0}if(p.type==='frost'){s.dmg=d.dmg+(l-1)*6;s.rate=Math.max(1050,d.rate-(l-1)*120);s.slow=d.slow+(l-1)*250}if(p.type==='laser'){s.dmg=d.dmg+(l-1)*10;s.rate=Math.max(1300,d.rate-(l-1)*150)}return s}
function plantAt(row,col,cell){audioStart();if(!isPlaying){sfx('deny');setMessage('Nhấn Bắt đầu chơi trước nhé.');return}const key=row+'-'+col,d=PLANTS[selectedPlant];if(plants.has(key)){sfx('deny');setMessage('Ô này đã có cây rồi.');return}if(!infiniteEnergy&&sun<d.cost){sfx('deny');setMessage('Chưa đủ năng lượng ☀️. Cần '+d.cost);return}if(!infiniteEnergy)sun-=d.cost;const p={type:selectedPlant,row,col,hp:d.hp,maxHp:d.hp,lastShoot:0,lastSun:performance.now(),el:document.createElement('div')};p.el.className='plant plant-'+selectedPlant;p.el.innerHTML=`<span class="sprite">${d.icon}</span><span class="hp"><i style="width:100%"></i></span>`;p.el.dataset.level=d.rate?'Lv.'+lvl():'';cell.appendChild(p.el);plants.set(key,p);updateHUD();sfx(selectedPlant==='bomb'?'boom':'plant');setMessage('Đã trồng '+selectedPlant)}
function rect(){return board.getBoundingClientRect()}function pos(r,c){const x=rect();return{x:(c+.5)*(x.width/COLS),y:(r+.5)*(x.height/ROWS)}}
function chooseZ(){if(wave%5===0&&!bossOut&&kills>=2){bossOut=true;return'boss'}let a=['basic'];if(wave>=2)a.push('fast');if(wave>=4)a.push('shield');if(wave>=6)a.push('armor');if(wave>=9)a.push('giant');return a[Math.floor(Math.random()*a.length)]}
function spawnZombie(){const t=chooseZ(),b=ZT[t],r=Math.floor(Math.random()*ROWS),x=rect(),scale=Math.min(wave,MAX_WAVE);const z={id:zid++,type:t,row:r,x:x.width+40,y:(r+.5)*(x.height/ROWS),hp:b.hp+scale*14,sp:b.sp+scale*.55,hit:b.hit,pt:b.pt,en:b.en,slowUntil:0,slowFactor:1,el:document.createElement('div')};z.el.className='zombie zombie-'+t;z.el.textContent=b.i;board.appendChild(z.el);zombies.push(z);if(t==='boss')sfx('boss')}
function shoot(p,off=0){const pp=pos(p.row,p.col),s=stats(p),q={row:p.row,x:pp.x+rect().width/COLS*.25,y:pp.y+off,sp:p.type==='laser'?310:235,dmg:s.dmg,pierce:!!s.pierce,slow:s.slow||0,hits:new Set(),el:document.createElement('div')};q.el.className='projectile projectile-'+p.type;board.appendChild(q.el);projectiles.push(q);sfx(p.type==='laser'?'laser':'shoot')}
function sunToken(r,c){const p=pos(r,c),e=document.createElement('button');e.className='sun-token';e.textContent='☀️';e.style.left=p.x-23+'px';e.style.top=p.y-23+'px';e.onclick=()=>{audioStart();sun+=25;e.remove();updateHUD();sfx('sun');setMessage('+25 năng lượng ☀️')};board.appendChild(e);setTimeout(()=>e.remove(),6500)}
function reward(z){score+=z.pt;if(!infiniteEnergy)sun+=z.en;kills++;sfx('kill');if(score>bestScore){bestScore=score;localStorage.setItem('gardenDefenseBest',bestScore)}if(kills>=KILLS_PER_WAVE){kills=0;bossOut=false;wave++;spawnEvery=Math.max(850,spawnEvery-170);sfx('wave');setMessage(wave===MAX_WAVE+1?'Đã qua 15 wave! Mở Endless Mode 👑':'Wave '+displayWave()+': zombie và súng đã nâng cấp ⚡')}updateHUD()}
function kill(z){const i=zombies.indexOf(z);if(i>=0){z.el.remove();zombies.splice(i,1);reward(z)}}function hurt(z,d){z.hp-=d;if(z.hp<=0)kill(z)}
function boom(p){const pp=pos(p.row,p.col),s=stats(p);plants.delete(p.row+'-'+p.col);p.el.remove();sfx('boom');zombies.slice().forEach(z=>{if(z.row===p.row&&Math.abs(z.x-pp.x)<180)hurt(z,s.dmg+wave*5)});setMessage('Cherry Bomb nổ cùng hàng 💥')}
function updatePlants(now){for(const p of plants.values()){const s=stats(p);if(p.el.dataset)p.el.dataset.level=s.rate?'Lv.'+s.l:'';if(p.type==='bomb'){const pp=pos(p.row,p.col);if(zombies.some(z=>z.row===p.row&&Math.abs(z.x-pp.x)<95))boom(p);continue}if(s.rate){const px=pos(p.row,p.col).x;if(zombies.some(z=>z.row===p.row&&z.x>px)&&now-p.lastShoot>s.rate){p.lastShoot=now;shoot(p);if(s.extra>=1)setTimeout(()=>shoot(p,-12),120);if(s.extra>=2)setTimeout(()=>shoot(p,12),220)}}if(p.type==='sun'&&now-p.lastSun>s.sunEvery){p.lastSun=now;sunToken(p.row,p.col)}}}
function updateZombies(dt,now){for(let i=zombies.length-1;i>=0;i--){const z=zombies[i],tar=[...plants.values()].filter(p=>p.row===z.row).find(p=>{const x=pos(p.row,p.col).x;return z.x>x-34&&z.x<x+48});if(tar){if(!z.lastHit||now-z.lastHit>780){z.lastHit=now;tar.hp-=z.hit;sfx('bite');tar.el.querySelector('.hp i').style.width=Math.max(0,tar.hp/tar.maxHp)*100+'%';if(tar.hp<=0){plants.delete(tar.row+'-'+tar.col);tar.el.remove();setMessage('Một cây đã bị zombie phá mất!')}}}else{const slow=now<z.slowUntil;z.el.classList.toggle('slow',slow);z.x-=z.sp*(slow?z.slowFactor:1)*dt}z.el.style.left=z.x-30+'px';z.el.style.top=z.y-33+'px';if(z.x<-30){z.el.remove();zombies.splice(i,1);lives--;sfx('deny');updateHUD();if(lives<=0)endGame()}}}
function updateProjectiles(dt,now){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.x+=p.sp*dt;const h=zombies.find(z=>z.row===p.row&&Math.abs(z.x-p.x)<24&&!p.hits.has(z.id));if(h){p.hits.add(h.id);if(p.slow){h.slowUntil=now+p.slow;h.slowFactor=.45}hurt(h,p.dmg);if(!p.pierce){p.el.remove();projectiles.splice(i,1);continue}}p.el.style.left=p.x-10+'px';p.el.style.top=p.y-10+'px';if(p.x>rect().width+50){p.el.remove();projectiles.splice(i,1)}}}
function loop(now){if(!isPlaying)return;const dt=Math.min(.04,(now-lastFrame)/1000);lastFrame=now;if(now-lastSpawn>spawnEvery){lastSpawn=now;spawnZombie()}updatePlants(now);updateZombies(dt,now);updateProjectiles(dt,now);requestAnimationFrame(loop)}
function startGame(){audioStart();sfx('start');isPlaying=true;sun=150;wave=1;kills=0;score=0;lives=5;spawnEvery=3500;bossOut=false;lastSpawn=performance.now();lastFrame=performance.now();plants.clear();zombies.splice(0).forEach(z=>z.el.remove());projectiles.splice(0).forEach(p=>p.el.remove());document.querySelectorAll('.zombie,.projectile,.sun-token,.pop').forEach(el=>el.remove());buildBoard();updateHUD();setMessage('Game bắt đầu: 15 wave chính 🌱');requestAnimationFrame(loop)}function endGame(){isPlaying=false;sfx('gameover');setMessage('Game over! Điểm của bạn: '+score+'. Nhấn Bắt đầu chơi để chơi lại.')}
initShop();if(energyToggle)energyToggle.onchange=()=>setEnergyMode(energyToggle.checked);if(hackModeButton)hackModeButton.onclick=()=>setEnergyMode(!infiniteEnergy);document.onkeydown=e=>{if(e.key.toLowerCase()==='h')setEnergyMode(!infiniteEnergy)};startBtn.onclick=startGame;buildBoard();updateHUD();setEnergyMode(false);
