const board=document.querySelector('#board');const startBtn=document.querySelector('#startBtn');const energyToggle=document.querySelector('.hero-actions input[type="checkbox"]');const message=document.querySelector('#message');const sunCountEl=document.querySelector('#sunCount');const waveCountEl=document.querySelector('#waveCount');const scoreCountEl=document.querySelector('#scoreCount');const lifeCountEl=document.querySelector('#lifeCount');const bestCountEl=document.querySelector('#bestCount');
const ROWS=5,COLS=9,ENERGY_REWARD=25;const PLANTS={pea:{icon:'🌿',cost:50,hp:125,shootEvery:1350,damage:24},sun:{icon:'🌻',cost:75,hp:95,sunEvery:6000},wall:{icon:'🪵',cost:40,hp:360}};
let selectedPlant='pea',sun=150,wave=1,score=0,lives=5,bestScore=Number(localStorage.getItem('gardenDefenseBest')||0),infiniteEnergy=false,isPlaying=false,lastFrame=performance.now(),lastSpawn=0,spawnEvery=3600;const cells=[],plants=new Map(),zombies=[],projectiles=[];
function buildBoard(){board.innerHTML='';cells.length=0;for(let r=0;r<ROWS;r++){for(let c=0;c<COLS;c++){const cell=document.createElement('button');cell.className='cell';cell.setAttribute('aria-label',`Ô hàng ${r+1}, cột ${c+1}`);cell.addEventListener('click',()=>plantAt(r,c,cell));board.appendChild(cell);cells.push(cell)}}}
function updateHUD(){sunCountEl.textContent=infiniteEnergy?'∞':sun;waveCountEl.textContent=wave;scoreCountEl.textContent=score;lifeCountEl.textContent=lives;if(bestCountEl)bestCountEl.textContent=bestScore}function setMessage(t){message.textContent=t}
function setEnergyMode(v){infiniteEnergy=v;if(energyToggle)energyToggle.checked=v;document.body.classList.toggle('hack-on',v);updateHUD();setMessage(v?'∞ Energy đã bật ⚡':'∞ Energy đã tắt 🌱')}
function plantAt(row,col,cell){if(!isPlaying){setMessage('Nhấn Bắt đầu chơi trước nhé.');return}const key=`${row}-${col}`,def=PLANTS[selectedPlant];if(plants.has(key)){setMessage('Ô này đã có cây rồi.');return}if(!infiniteEnergy&&sun<def.cost){setMessage(`Chưa đủ năng lượng ☀️. Cần ${def.cost}.`);return}if(!infiniteEnergy)sun-=def.cost;const plant={type:selectedPlant,row,col,hp:def.hp,maxHp:def.hp,lastShoot:0,lastSun:performance.now(),el:document.createElement('div')};plant.el.className=`plant plant-${selectedPlant}`;plant.el.innerHTML=`<span class="sprite">${def.icon}</span><span class="hp"><i style="width:100%"></i></span>`;cell.appendChild(plant.el);plants.set(key,plant);updateHUD();const p=cellPosition(row,col);showPop(p.x,p.y,infiniteEnergy?'∞':`-${def.cost}☀️`);setMessage(infiniteEnergy?'Đã trồng cây với ∞ Energy ⚡':'Đã trồng cây. Giữ vườn nào! 🌱')}
document.querySelectorAll('.plant-card').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.plant-card').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');selectedPlant=btn.dataset.plant;setMessage(`Đã chọn ${btn.querySelector('b').textContent}.`)}));if(energyToggle)energyToggle.addEventListener('change',()=>setEnergyMode(energyToggle.checked));document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h')setEnergyMode(!infiniteEnergy)});
function boardRect(){return board.getBoundingClientRect()}function cellPosition(row,col){const rect=boardRect();return{x:(col+.5)*(rect.width/COLS),y:(row+.5)*(rect.height/ROWS)}}
function spawnZombie(){const row=Math.floor(Math.random()*ROWS),rect=boardRect(),hp=78+wave*16,speed=12+wave*1.3;const z={row,x:rect.width+30,y:(row+.5)*(rect.height/ROWS),hp,maxHp:hp,speed,damageEvery:780,lastDamage:0,el:document.createElement('div')};z.el.className='zombie';z.el.textContent=wave>=4&&Math.random()>.55?'🧟‍♂️':'🧟';board.appendChild(z.el);zombies.push(z)}
function createProjectile(plant){const rect=boardRect(),pos=cellPosition(plant.row,plant.col);const p={row:plant.row,x:pos.x+rect.width/COLS*.25,y:pos.y,speed:235,damage:PLANTS[plant.type].damage,el:document.createElement('div')};p.el.className='projectile';board.appendChild(p.el);projectiles.push(p)}
function createSunToken(row,col){const pos=cellPosition(row,col),token=document.createElement('button');token.className='sun-token';token.textContent='☀️';token.style.left=`${pos.x-23}px`;token.style.top=`${pos.y-23}px`;token.addEventListener('click',()=>{sun+=25;token.remove();updateHUD();showPop(pos.x,pos.y,'+25☀️');setMessage('+25 năng lượng ☀️')});board.appendChild(token);setTimeout(()=>token.remove(),6500)}
function showPop(x,y,text){const pop=document.createElement('div');pop.className='pop';pop.textContent=text;pop.style.left=`${x-18}px`;pop.style.top=`${y-24}px`;board.appendChild(pop);setTimeout(()=>pop.remove(),850)}
function updatePlants(now){for(const plant of plants.values()){const def=PLANTS[plant.type];if(plant.type==='pea'){const plantX=cellPosition(plant.row,plant.col).x;const hasZombie=zombies.some(z=>z.row===plant.row&&z.x>plantX);if(hasZombie&&now-plant.lastShoot>def.shootEvery){plant.lastShoot=now;createProjectile(plant)}}if(plant.type==='sun'&&now-plant.lastSun>def.sunEvery){plant.lastSun=now;createSunToken(plant.row,plant.col)}}}
function updateZombies(dt,now){for(let i=zombies.length-1;i>=0;i--){const z=zombies[i];const target=[...plants.values()].filter(p=>p.row===z.row).find(p=>{const x=cellPosition(p.row,p.col).x;return z.x>x-32&&z.x<x+46});if(target){if(now-z.lastDamage>z.damageEvery){z.lastDamage=now;target.hp-=25;target.el.querySelector('.hp i').style.width=`${Math.max(0,target.hp/target.maxHp)*100}%`;if(target.hp<=0){plants.delete(`${target.row}-${target.col}`);target.el.remove();setMessage('Một cây đã bị zombie ăn mất! 🧟')}}}else{z.x-=z.speed*dt}z.el.style.left=`${z.x-30}px`;z.el.style.top=`${z.y-33}px`;if(z.x<-30){z.el.remove();zombies.splice(i,1);lives-=1;updateHUD();setMessage('Zombie lọt vào nhà! Mất 1 ❤️');if(lives<=0)endGame()}}}
function updateProjectiles(dt){const rect=boardRect();for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.x+=p.speed*dt;const hitIndex=zombies.findIndex(z=>z.row===p.row&&Math.abs(z.x-p.x)<24);if(hitIndex>=0){const z=zombies[hitIndex];z.hp-=p.damage;p.el.remove();projectiles.splice(i,1);if(z.hp<=0){const hx=z.x,hy=z.y;z.el.remove();zombies.splice(hitIndex,1);score+=10;showPop(hx,hy,'+10');if(!infiniteEnergy){sun+=ENERGY_REWARD;showPop(hx,hy-28,`+${ENERGY_REWARD}☀️`);setMessage(`Zombie bị hạ! +${ENERGY_REWARD} năng lượng ☀️`)}if(score>bestScore){bestScore=score;localStorage.setItem('gardenDefenseBest',bestScore)}if(score>0&&score%80===0){wave+=1;spawnEvery=Math.max(1200,spawnEvery-360);setMessage(`Wave ${wave}! Zombie nhanh hơn rồi đó ⚡`)}updateHUD()}continue}p.el.style.left=`${p.x-10}px`;p.el.style.top=`${p.y-10}px`;if(p.x>rect.width+30){p.el.remove();projectiles.splice(i,1)}}}
function loop(now){if(!isPlaying)return;const dt=Math.min(.04,(now-lastFrame)/1000);lastFrame=now;if(now-lastSpawn>spawnEvery){lastSpawn=now;spawnZombie()}updatePlants(now);updateZombies(dt,now);updateProjectiles(dt);requestAnimationFrame(loop)}
function startGame(){isPlaying=true;sun=150;wave=1;score=0;lives=5;spawnEvery=3600;lastSpawn=performance.now();lastFrame=performance.now();plants.clear();zombies.splice(0).forEach(z=>z.el.remove());projectiles.splice(0).forEach(p=>p.el.remove());document.querySelectorAll('.zombie,.projectile,.sun-token,.pop').forEach(el=>el.remove());buildBoard();updateHUD();setMessage(infiniteEnergy?'Game bắt đầu với ∞ Energy ⚡':'Game bắt đầu! Trồng cây thật nhanh nhé 🌱');requestAnimationFrame(loop)}function endGame(){isPlaying=false;setMessage(`Game over! Điểm của bạn: ${score}. Nhấn Bắt đầu chơi để chơi lại.`)}
startBtn.addEventListener('click',startGame);buildBoard();updateHUD();
