const board=document.querySelector('#board');const startBtn=document.querySelector('#startBtn');const message=document.querySelector('#message');const sunCountEl=document.querySelector('#sunCount');const waveCountEl=document.querySelector('#waveCount');const scoreCountEl=document.querySelector('#scoreCount');const lifeCountEl=document.querySelector('#lifeCount');
const ROWS=5,COLS=9;const PLANTS={pea:{icon:'🌿',cost:50,hp:120,shootEvery:1500,damage:22},sun:{icon:'🌻',cost:75,hp:90,sunEvery:6500},wall:{icon:'🪵',cost:40,hp:330}};
let selectedPlant='pea',sun=150,wave=1,score=0,lives=5,isPlaying=false,lastFrame=performance.now(),lastSpawn=0,spawnEvery=3600;const cells=[],plants=new Map(),zombies=[],projectiles=[];
function buildBoard(){board.innerHTML='';cells.length=0;for(let r=0;r<ROWS;r++){for(let c=0;c<COLS;c++){const cell=document.createElement('button');cell.className='cell';cell.setAttribute('aria-label',`Ô hàng ${r+1}, cột ${c+1}`);cell.addEventListener('click',()=>plantAt(r,c,cell));board.appendChild(cell);cells.push(cell)}}}
function updateHUD(){sunCountEl.textContent=sun;waveCountEl.textContent=wave;scoreCountEl.textContent=score;lifeCountEl.textContent=lives}function setMessage(t){message.textContent=t}
function plantAt(row,col,cell){if(!isPlaying){setMessage('Nhấn Bắt đầu chơi trước nhé.');return}const key=`${row}-${col}`,def=PLANTS[selectedPlant];if(plants.has(key)){setMessage('Ô này đã có cây rồi.');return}if(sun<def.cost){setMessage(`Chưa đủ năng lượng ☀️. Cần ${def.cost}.`);return}sun-=def.cost;const plant={type:selectedPlant,row,col,hp:def.hp,maxHp:def.hp,lastShoot:0,lastSun:performance.now(),el:document.createElement('div')};plant.el.className='plant';plant.el.innerHTML=`${def.icon}<span class="hp"><i style="width:100%"></i></span>`;cell.appendChild(plant.el);plants.set(key,plant);updateHUD();setMessage('Đã trồng cây. Giữ vườn nào! 🌱')}
document.querySelectorAll('.plant-card').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.plant-card').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');selectedPlant=btn.dataset.plant;setMessage(`Đã chọn ${btn.querySelector('b').textContent}.`)}));
function boardRect(){return board.getBoundingClientRect()}function cellPosition(row,col){const rect=boardRect();return{x:(col+.5)*(rect.width/COLS),y:(row+.5)*(rect.height/ROWS)}}
function spawnZombie(){const row=Math.floor(Math.random()*ROWS),rect=boardRect(),hp=75+wave*15,speed=12+wave*1.25;const z={row,x:rect.width+30,y:(row+.5)*(rect.height/ROWS),hp,maxHp:hp,speed,damageEvery:800,lastDamage:0,el:document.createElement('div')};z.el.className='zombie';z.el.textContent='🧟';board.appendChild(z.el);zombies.push(z)}
function createProjectile(plant){const rect=boardRect(),pos=cellPosition(plant.row,plant.col);const p={row:plant.row,x:pos.x+rect.width/COLS*.25,y:pos.y,speed:220,damage:PLANTS[plant.type].damage,el:document.createElement('div')};p.el.className='projectile';board.appendChild(p.el);projectiles.push(p)}
function createSunToken(row,col){const pos=cellPosition(row,col),token=document.createElement('button');token.className='sun-token';token.textContent='☀️';token.style.left=`${pos.x-21}px`;token.style.top=`${pos.y-21}px`;token.addEventListener('click',()=>{sun+=25;token.remove();updateHUD();setMessage('+25 năng lượng ☀️')});board.appendChild(token);setTimeout(()=>token.remove(),6000)}
function updatePlants(now){for(const plant of plants.values()){const def=PLANTS[plant.type];if(plant.type==='pea'){const hasZombie=zombies.some(z=>z.row===plant.row&&z.x>cellPosition(plant.row,plant.col).x);if(hasZombie&&now-plant.lastShoot>def.shootEvery){plant.lastShoot=now;createProjectile(plant)}}if(plant.type==='sun'&&now-plant.lastSun>def.sunEvery){plant.lastSun=now;createSunToken(plant.row,plant.col)}}}
function updateZombies(dt,now){for(let i=zombies.length-1;i>=0;i--){const z=zombies[i];const target=[...plants.values()].filter(p=>p.row===z.row).find(p=>{const x=cellPosition(p.row,p.col).x;return z.x>x-32&&z.x<x+46});if(target){if(now-z.lastDamage>z.damageEvery){z.lastDamage=now;target.hp-=26;target.el.querySelector('.hp i').style.width=`${Math.max(0,target.hp/target.maxHp)*100}%`;if(target.hp<=0){plants.delete(`${target.row}-${target.col}`);target.el.remove();setMessage('Một cây đã bị zombie ăn mất! 🧟')}}}else{z.x-=z.speed*dt}z.el.style.left=`${z.x-28}px`;z.el.style.top=`${z.y-31}px`;if(z.x<-30){z.el.remove();zombies.splice(i,1);lives-=1;updateHUD();setMessage('Zombie lọt vào nhà! Mất 1 ❤️');if(lives<=0)endGame()}}}
function updateProjectiles(dt){const rect=boardRect();for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.x+=p.speed*dt;const hitIndex=zombies.findIndex(z=>z.row===p.row&&Math.abs(z.x-p.x)<24);if(hitIndex>=0){const z=zombies[hitIndex];z.hp-=p.damage;p.el.remove();projectiles.splice(i,1);if(z.hp<=0){z.el.remove();zombies.splice(hitIndex,1);score+=10;if(score>0&&score%80===0){wave+=1;spawnEvery=Math.max(1300,spawnEvery-350);setMessage(`Wave ${wave}! Zombie nhanh hơn rồi đó ⚡`)}updateHUD()}continue}p.el.style.left=`${p.x-10}px`;p.el.style.top=`${p.y-10}px`;if(p.x>rect.width+30){p.el.remove();projectiles.splice(i,1)}}}
function loop(now){if(!isPlaying)return;const dt=Math.min(.04,(now-lastFrame)/1000);lastFrame=now;if(now-lastSpawn>spawnEvery){lastSpawn=now;spawnZombie()}updatePlants(now);updateZombies(dt,now);updateProjectiles(dt);requestAnimationFrame(loop)}
function startGame(){isPlaying=true;sun=150;wave=1;score=0;lives=5;spawnEvery=3600;lastSpawn=performance.now();lastFrame=performance.now();plants.clear();zombies.splice(0).forEach(z=>z.el.remove());projectiles.splice(0).forEach(p=>p.el.remove());document.querySelectorAll('.zombie,.projectile,.sun-token').forEach(el=>el.remove());buildBoard();updateHUD();setMessage('Game bắt đầu! Trồng cây thật nhanh nhé 🌱');requestAnimationFrame(loop)}function endGame(){isPlaying=false;setMessage(`Game over! Điểm của bạn: ${score}. Nhấn Bắt đầu chơi để chơi lại.`)}
startBtn.addEventListener('click',startGame);buildBoard();updateHUD();
